INSERT INTO AsignaYasegura_usuario(ci,nombre,apellidos,usuario_id,direccion,telefono,correo) VALUES('0923261382','mauricio','leiton',1,'data de villamil','0989389265','mau_leiton96@hotmail.com');
INSERT INTO AsignaYasegura_usuariorol(usuario_id,rol_id) VALUES ('0923261382',1);
INSERT INTO AsignaYasegura_distrito( codigo, nombre, zona,cantidadinstituciones ) VALUES ( 'c1','ximena 1','8',12);
INSERT INTO AsignaYasegura_distrito( codigo, nombre, zona,cantidadinstituciones ) VALUES ( 'c2','ximena 2','8',14);
INSERT INTO AsignaYasegura_distrito( codigo, nombre, zona,cantidadinstituciones ) VALUES ( 'c3','Antigua direccion provincial de educacion','8',16);
INSERT INTO AsignaYasegura_distrito( codigo, nombre, zona,cantidadinstituciones ) VALUES ( 'c4','Portete','8',2);
INSERT INTO AsignaYasegura_distrito( codigo, nombre, zona,cantidadinstituciones ) VALUES ( 'c5','Tarqui','8',89);
INSERT INTO AsignaYasegura_distrito( codigo, nombre, zona,cantidadinstituciones ) VALUES ( 'c6','Bellavista-mapasingue','8',56);
INSERT INTO AsignaYasegura_distrito( codigo, nombre, zona,cantidadinstituciones ) VALUES ( 'c7','Vergeles','8',23);
INSERT INTO AsignaYasegura_distrito( codigo, nombre, zona,cantidadinstituciones ) VALUES ( 'c8','Monte siani','8',1);
INSERT INTO AsignaYasegura_distrito( codigo, nombre, zona,cantidadinstituciones ) VALUES ( 'c9','Chongon','8',2);
INSERT INTO AsignaYasegura_distrito( codigo, nombre, zona,cantidadinstituciones ) VALUES ( 'c10','Gomez rendon','8',3);
INSERT INTO AsignaYasegura_distrito( codigo, nombre, zona,cantidadinstituciones ) VALUES ( 'c23','Samborondon','8',5);
INSERT INTO AsignaYasegura_distrito( codigo, nombre, zona,cantidadinstituciones ) VALUES ( 'c24','Duran','8',5);
INSERT INTO AsignaYasegura_ofertaacademica( nombre) VALUES ( 'Bachillerato General Unificado');
INSERT INTO AsignaYasegura_ofertaacademica( nombre) VALUES ( 'Bachillerato Internacional');
INSERT INTO AsignaYasegura_ofertaacademica( nombre) VALUES ( 'Bachillerato Técnico');
INSERT INTO AsignaYasegura_carrerastecnicas( nombre,ofertaacademica_id ) VALUES ( 'Producción agropecuaria','3');
INSERT INTO AsignaYasegura_carrerastecnicas( nombre,ofertaacademica_id ) VALUES ('Conservación y manejo de recursos naturales','3');
INSERT INTO AsignaYasegura_carrerastecnicas( nombre,ofertaacademica_id ) VALUES ( 'Industrialización de productos alimenticios','3');
INSERT INTO AsignaYasegura_carrerastecnicas( nombre,ofertaacademica_id ) VALUES ( 'Promotor en recreación y deportes','3');
INSERT INTO AsignaYasegura_carrerastecnicas( nombre,ofertaacademica_id ) VALUES ( 'Electromecánica automotriz','3');
INSERT INTO AsignaYasegura_carrerastecnicas( nombre,ofertaacademica_id ) VALUES ( 'Chapisteria y pintura','3');
INSERT INTO AsignaYasegura_carrerastecnicas( nombre,ofertaacademica_id ) VALUES ( 'Climatizacion','3');
INSERT INTO AsignaYasegura_carrerastecnicas( nombre,ofertaacademica_id ) VALUES ( 'Electrónica de consumo','3');
INSERT INTO AsignaYasegura_carrerastecnicas( nombre,ofertaacademica_id ) VALUES ( 'Aplicación de proyectos de producción','3');
INSERT INTO AsignaYasegura_carrerastecnicas( nombre,ofertaacademica_id ) VALUES ( 'Fabricación y montaje de muebles','3');
INSERT INTO AsignaYasegura_carrerastecnicas( nombre,ofertaacademica_id ) VALUES ( 'Industria de la confección','3');
INSERT INTO AsignaYasegura_carrerastecnicas( nombre,ofertaacademica_id ) VALUES ( 'Calzado y marroquinería','3');
INSERT INTO AsignaYasegura_carrerastecnicas( nombre,ofertaacademica_id ) VALUES ( 'Mecanizado y construcciones metálicas','3');
INSERT INTO AsignaYasegura_carrerastecnicas( nombre,ofertaacademica_id ) VALUES ( 'Industria textil','3');
INSERT INTO AsignaYasegura_carrerastecnicas( nombre,ofertaacademica_id ) VALUES ( 'Instalaciones, equipos y máquinas eléctricas','3');
INSERT INTO AsignaYasegura_roles(rol,descripcion) values('administrador','registra a los digitadores y ejecuta la opcion asignacion ');
INSERT INTO AsignaYasegura_roles(rol,descripcion) values('padre de familia','registra a sus hijos y puede ver el colegio asignado para cada hijo.');
INSERT INTO AsignaYasegura_roles(rol,descripcion) values('digitador','registra la informacion y capacidades de cada una de las instituciones educativas');
INSERT INTO AsignaYasegura_permiso(permiso,descripcion) VALUES ( 'Registrar estudiantes','permite registrar padres de familias de escasos recursos');
INSERT INTO AsignaYasegura_permiso(permiso,descripcion) VALUES ( 'Registrar instituciones','permite registrar instituciones/capacidades de las escuelas');
INSERT INTO AsignaYasegura_permiso(permiso,descripcion) VALUES ( 'Inspecciones','permite inspeccionar instituciones de las escuelas');
INSERT INTO AsignaYasegura_instruccion(tipo) VALUES ( 'primaria');
INSERT INTO AsignaYasegura_instruccion(tipo) VALUES ( 'secundaria');
INSERT INTO AsignaYasegura_nivel(nivel) VALUES ('Preparatoria');
INSERT INTO AsignaYasegura_nivel(nivel) VALUES ('Básica elemental');
INSERT INTO AsignaYasegura_nivel(nivel) VALUES ('Básica media');
INSERT INTO AsignaYasegura_nivel(nivel) VALUES ('Básica superior');
INSERT INTO AsignaYasegura_nivel(nivel) VALUES ('Bachillerato');
INSERT INTO AsignaYasegura_jornada(jornada) VALUES ('matutina');
INSERT INTO AsignaYasegura_jornada(jornada) VALUES ('vespertina');
INSERT INTO AsignaYasegura_capacidadestandar( capacidad, nivel_id) VALUES( 25,1);
INSERT INTO AsignaYasegura_capacidadestandar( capacidad, nivel_id) VALUES( 30,2);
INSERT INTO AsignaYasegura_capacidadestandar( capacidad, nivel_id) VALUES( 35,3);
INSERT INTO AsignaYasegura_capacidadestandar( capacidad, nivel_id) VALUES( 45,4);
INSERT INTO AsignaYasegura_capacidadestandar( capacidad, nivel_id) VALUES( 45,5);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Primer año básico',2,1);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Segundo año básico',2,1);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Tercer año básico',2,1);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Cuarto año básico',2,1);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Quinto año básico',2,1);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Sexto año básico',2,1);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Septimo año básico',2,1);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Octavo año básico',2,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Noveno año básico',2,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Decimoo año básico',2,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('B.G.U. 1',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('B.G.U. 2',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('B.G.U. 3',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('B.I. 1',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('B.I. 2',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('B.I. 3',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Primer año B.T. Produccion agropecuaria',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Segundo año B.T. Produccion agropecuaria',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Tercer año B.T. Produccion agropecuaria',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Primer año B.T. Conservación y manejo de recursos naturales',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Segundo año B.T. Conservación y manejo de recursos naturales',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Tercer año B.T. Conservación y manejo de recursos naturales',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Primer año B.T. Industrialización de productos alimenticios',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Segundo año B.T. Industrialización de productos alimenticios',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Tercer año B.T. Industrialización de productos alimenticios',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Primer año B.T. Promotor en recreación y deportes',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Segundo año B.T. Promotor en recreación y deportes',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Tercer año B.T. Promotor en recreación y deportes',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Primer año B.T. Electromecánica automotriz',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Segundo año B.T. Electromecánica automotriz',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Tercer año B.T. Electromecánica automotriz',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Primer año B.T. Chapisteria y pintura',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Segundo año B.T. Chapisteria y pintura',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Tercer año B.T. Chapisteria y pintura',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Primer año B.T. Climatizacion',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Segundo año B.T. Climatizacion',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Tercer año B.T. Climatizacion',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Primer año B.T. Electrónica de consumo',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Segundo año B.T. Electrónica de consumo',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Tercer año B.T. Electrónica de consumo',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Primer año B.T. Aplicación de proyectos de producción',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Segundo año B.T. Aplicación de proyectos de producción',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Tercer año B.T. Aplicación de proyectos de producción',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Primer año B.T. Fabricación y montaje de muebles',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Segundo año B.T. Fabricación y montaje de muebles',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Tercer año B.T. Fabricación y montaje de muebles',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Primer año B.T. Industria de la confección',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Segundo año B.T. Industria de la confección',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Tercer año B.T. Industria de la confección',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Primer año B.T. Calzado y marroquinería',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Segundo año B.T. Calzado y marroquinería',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Tercer año B.T. Calzado y marroquinería',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Primer año B.T. Mecanizado y construcciones metálicas',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Segundo año B.T. Mecanizado y construcciones metálicas',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Tercer año B.T. Mecanizado y construcciones metálicas',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Primer año B.T. Industria textil',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Segundo año B.T. Industria textil',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Tercer año B.T. Industria textil',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Primer año B.T. Instalaciones, equipos y máquinas eléctricas',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Segundo año B.T. Instalaciones, equipos y máquinas eléctricas',5,2);
INSERT INTO AsignaYasegura_curso(curso,nivel_id,instruccion_id) VALUES ('Tercer año B.T. Instalaciones, equipos y máquinas eléctricas',5,2);