# Generated by Django 2.0.1 on 2018-01-21 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id_aula', models.AutoField(primary_key=True, serialize=False)),
                ('capacidadmax', models.IntegerField()),
                ('capacidadpupitres', models.IntegerField()),
                ('longitud', models.FloatField()),
                ('amplitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AulajornadaCurso',
            fields=[
                ('id_aulacurso', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField()),
                ('paralelo', models.CharField(max_length=35)),
                ('cupos', models.IntegerField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AsignaYasegura.Aula')),
            ],
        ),
        migrations.CreateModel(
            name='CapacidadEstandar',
            fields=[
                ('id_capacidad', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarrerasTecnicas',
            fields=[
                ('idcarrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('codigo', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('zona', models.CharField(max_length=35)),
                ('distrito', models.CharField(max_length=35)),
                ('cantidadinstituciones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('ci', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('apellidos', models.CharField(max_length=35)),
                ('telefono', models.CharField(max_length=13)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('discapacidad', models.CharField(max_length=35)),
                ('porcentaje', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('ci', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nacimiento', models.DateTimeField()),
                ('nombre', models.CharField(max_length=35)),
                ('apellidos', models.CharField(max_length=35)),
                ('direccion', models.CharField(max_length=100)),
                ('parentescorepresentante', models.CharField(max_length=100)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AsignaYasegura.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='EstudiantePostulacion',
            fields=[
                ('id_postulacion', models.AutoField(primary_key=True, serialize=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AsignaYasegura.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id_institucion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('naulas', models.IntegerField()),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('carreras', models.ManyToManyField(to='AsignaYasegura.CarrerasTecnicas')),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AsignaYasegura.Circuito')),
            ],
        ),
        migrations.CreateModel(
            name='Instruccion',
            fields=[
                ('id_instruccion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('idjornada', models.AutoField(primary_key=True, serialize=False)),
                ('jornada', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaAcademica',
            fields=[
                ('id_institucion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PadreInfo',
            fields=[
                ('id_padre', models.AutoField(primary_key=True, serialize=False)),
                ('condicionp', models.CharField(max_length=100)),
                ('registropropiedad', models.CharField(max_length=100)),
                ('parentescop', models.CharField(max_length=100)),
                ('codigoluz', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('permiso', models.CharField(max_length=35)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemasAsignacion',
            fields=[
                ('id_problemas', models.AutoField(primary_key=True, serialize=False)),
                ('problema', models.CharField(max_length=40)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AsignaYasegura.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('aulajornadacurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AsignaYasegura.AulajornadaCurso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AsignaYasegura.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=35)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ci', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('apellidos', models.CharField(max_length=35)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=13)),
                ('correo', models.EmailField(max_length=254)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuariopermisos',
            fields=[
                ('id_usuario_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AsignaYasegura.Permiso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AsignaYasegura.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuariorol',
            fields=[
                ('id_usuario_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AsignaYasegura.Roles')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AsignaYasegura.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='padreinfo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AsignaYasegura.Usuario'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='instruccion',
            field=models.ManyToManyField(to='AsignaYasegura.Instruccion'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='jornada',
            field=models.ManyToManyField(to='AsignaYasegura.Jornada'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='ofertaacademica',
            field=models.ManyToManyField(to='AsignaYasegura.OfertaAcademica'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='representante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AsignaYasegura.Director'),
        ),
        migrations.AddField(
            model_name='estudiantepostulacion',
            name='opcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AsignaYasegura.Institucion'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='representante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AsignaYasegura.Usuario'),
        ),
        migrations.AddField(
            model_name='discapacidad',
            name='estudiante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AsignaYasegura.Estudiante'),
        ),
        migrations.AddField(
            model_name='curso',
            name='instruccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AsignaYasegura.Instruccion'),
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AsignaYasegura.Nivel'),
        ),
        migrations.AddField(
            model_name='carrerastecnicas',
            name='ofertaacademica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AsignaYasegura.OfertaAcademica'),
        ),
        migrations.AddField(
            model_name='capacidadestandar',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AsignaYasegura.Nivel'),
        ),
        migrations.AddField(
            model_name='aulajornadacurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AsignaYasegura.Curso'),
        ),
        migrations.AddField(
            model_name='aulajornadacurso',
            name='jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AsignaYasegura.Jornada'),
        ),
        migrations.AddField(
            model_name='aula',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AsignaYasegura.Institucion'),
        ),
    ]
