# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsignaYasegura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='parentescorepresentante',
            field=models.CharField(default='padres', max_length=100),
            preserve_default=False,
        ),
    ]
