# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsignaYasegura', '0002_estudiante_parentescorepresentante'),
    ]

    operations = [
        migrations.AddField(
            model_name='padreinfo',
            name='registropropiedad',
            field=models.CharField(default='245643', max_length=100),
            preserve_default=False,
        ),
    ]
