# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsignaYasegura', '0003_padreinfo_registropropiedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='geolocalizacionpadre',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='geolocalizacionpadre',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='geolocalizacionpadre',
            name='longitud',
        ),
        migrations.AddField(
            model_name='padreinfo',
            name='direccion',
            field=models.CharField(default='data de villamil,playas,guayas', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='padreinfo',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='padreinfo',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
