# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AsignaYasegura', '0004_auto_20171015_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocalizacionpadre',
            name='padre',
        ),
        migrations.DeleteModel(
            name='GeolocalizacionPadre',
        ),
    ]
